version: "3.8"
services:
  reviews-feature:
    image: reviews
    stdin_open: true
    ports:
      - "1128:1128"
    depends_on:
      - mongo
  mongo:
    image : mongo:3.6.19-xenial
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
    driver: local


